MAINT-27983: UI inconsistencies between different pages
Meeds-io/platform-ui pull request #162
Opened 2020-10-05 08:31 UTC by Rdidmohamedelhadi

(cherry picked from commit fd0ba697b47f5230f72f32a9353ceda945e4c4cf)

2020-10-05 08:33 UTC, mzorai approved these changes

2020-10-05 08:51 UTC, ahamdi approved these changes

2020-10-05 08:52 UTC, azayati requested changes
Please consider this [PR ](https://github.com/Meeds-io/platform-ui/pull/159)

2020-10-06 08:45 UTC, azayati approved these changes
LGTM

2020-10-06 09:12 UTC, merged