Task-41306 : Add source column on UserManegement
Meeds-io/platform-ui pull request #227
Opened 2021-03-10 14:07 UTC by ahmadmido

This PR will add a new column on UserManegmenet table -> Source.
This column will check if a user is an internal user or a synchronized user, if is internal we display an icon with eXo logo and if's synchronized LDAP/AD we display an icon with a tag SYNC.

2021-03-11 08:23 UTC, rdenarie submitted a review, later dismissed

2021-03-14 19:39 UTC, rdenarie submitted a review, later dismissed

2021-03-17 08:09 UTC, azayati requested changes
See review

2021-03-17 08:09 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/portlets/IDMUsersManagement/Style.less
> +    font-family: Arial, Helvetica, sans-serif;
do you need font-family ?

2021-03-17 08:09 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/portlets/IDMUsersManagement/Style.less
> +    font-family: Arial, Helvetica, sans-serif;
do you need font-family ?

2021-03-17 14:52 UTC, azayati approved these changes
LGTM

2021-03-17 14:54 UTC, merged