Task-41617 : Enlarge the user mangement table by adding new container
Meeds-io/platform-ui pull request #229
Opened 2021-03-17 14:39 UTC by ahmadmido

This fix will enlarge the user management table by adding a container.

2021-03-26 10:00 UTC, plamarque requested changes, later dismissed

2021-03-26 10:00 UTC, plamarque commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/SocialPage/Style.less
> +#singlePageApplicationContainer, #singlePageUserManegementApplicationContainer, .singlePageApplication, .SpaceActivityStreamPortletPage {
```suggestion
#singlePageApplicationContainer, #singlePageUserManagementApplicationContainer, .singlePageApplication, .SpaceActivityStreamPortletPage {
```

2021-03-26 10:00 UTC, plamarque commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/SocialPage/Style.less
> +  #singlePageUserManegementApplicationContainer {
```suggestion
  #singlePageUserManagementApplicationContainer {
```

2021-03-26 10:00 UTC, plamarque commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/SocialPage/Style.less
> +  #singlePageUserManegementApplicationContainer {
```suggestion
  #singlePageUserManagementApplicationContainer {
```

2021-03-29 15:27 UTC, rdenarie requested changes

2021-03-29 15:27 UTC, rdenarie commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/SocialPage/Style.less
> +#singlePageApplicationContainer, #singlePageUserManagementApplicationContainer, .singlePageApplication, .SpaceActivityStreamPortletPage {
does this modification is still needed ?

2021-03-29 15:27 UTC, rdenarie commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/SocialPage/Style.less
> +
does this modification is still needed ?

2021-03-30 15:56 UTC, rdenarie approved these changes

2021-03-31 14:27 UTC, merged