Task-42849: Add share activity icon and fix css of the display of the shared activity
Meeds-io/platform-ui pull request #249
Opened 2021-05-10 15:04 UTC by hassenelkamel-exo

- Add share activity icon
- Fix css of the display of the shared activity

2021-05-11 08:44 UTC, azayati requested changes
See review

2021-05-11 08:44 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/Activity/Style.less
> +      border: 1px solid #e1e8ee;
use a color variable instead

2021-05-11 08:44 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/Activity/Style.less
> +    .shareActivityContainer {
Try to use css util classes

2021-05-11 08:47 UTC, hassenelkamel-exo commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/Activity/Style.less
> +    .shareActivityContainer {
it is in gtmpl, we cannot use it

2021-05-17 16:16 UTC, azayati approved these changes, later dismissed
LGTM until QA validation

2021-05-18 09:34 UTC, azayati approved these changes
LGTM

2021-05-18 09:35 UTC, merged