fix-38380: New composer : insert youtube link .
Meeds-io/platform-ui pull request #376
Opened 2022-02-17 14:19 UTC by IlhemEssaadi

ISSUES : added a css class named video to fix the position of the video in the post content.

2022-02-21 14:43 UTC, rdenarie requested changes
Why do you add this css rule ?

2022-02-22 09:42 UTC, IlhemEssaadi commented
> Why do you add this css rule ?

the content of the post can contain a video that's why I added a video class to postContenet to fixing the marging left of video.

2022-02-23 09:37 UTC, rdenarie commented
When you say a "post", do you mean a "news" or an "activity" ?
In addition, my problem is that this class is used without any context. So if someone else use this class, we will have a conflict. 
"video" is a commun word, and I'm afraid of conflict.

Finally, for margin, vue provide some helper classes : https://vuetifyjs.com/en/styles/spacing/#how-it-works
So, can we use theses helpers class instead of video class ? and we should also take care of rtl-ization

2022-02-23 09:37 UTC, rdenarie requested changes
See my last comment

2022-03-01 11:04 UTC, rdenarie requested changes
Can you rebase the PR ?

2022-03-01 11:08 UTC, IlhemEssaadi commented
> Can you rebase the PR ?

Done !!

2022-03-01 14:39 UTC, rdenarie approved these changes

2022-03-01 14:40 UTC, rdenarie requested changes
You need to take care of rtl. 
Please add the css for the margin-right also

2022-03-02 11:50 UTC, IlhemEssaadi commented
> You need to take care of rtl. Please add the css for the margin-right also

tested , no need to add margin-right because for all rtlisation we just need to add margin-left .

2022-03-02 14:04 UTC, rdenarie requested changes
You need to take care of rtl.
Please add the css for the margin-right also

2022-03-02 14:07 UTC, rdenarie commented
> > You need to take care of rtl. Please add the css for the margin-right also
> 
> tested , no need to add margin-right because for all rtlisation we just need to add margin-left .

how the margin-left is transformed to margin-right when you use right to left ?
Can you show me a screenshot with right-to-left ?

2022-03-03 09:57 UTC, rdenarie requested changes

2022-03-03 09:57 UTC, rdenarie commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/Activity/Style.less
> +    }
No need to use flex here. Use the same behaviour as we already have with the embedded object : 
```suggestion
    .video {
      width:320px;
      margin-left:auto;
      margin-right:auto;
    }
```

2022-08-16 13:49 UTC, closed without merging