feat: Implement Simple Column container - EXO-61140 - Meeds-io/MIPs#37
Meeds-io/platform-ui pull request #555
Opened 2022-12-19 15:26 UTC by sofyenne

2022-12-20 10:14 UTC, azayati requested changes

2022-12-20 10:14 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/platform/skin/uiSimpleContainers/simpleColumnContainer.less
> +  .UIContainer.SimpleColumnContainer {
indentation

2022-12-20 10:14 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/platform/skin/uiSimpleContainers/simpleColumnContainer.less
> +.UIContainer.SimpleColumnContainer {
indentation

2022-12-20 10:14 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/component/Portal/UIEditInlineWS/Style.less
> +			background-position: 5px -401px;
to be verified with PO

2022-12-21 15:17 UTC, azayati requested changes

2022-12-21 15:17 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/platform/skin/uiSimpleContainers/responsiveColumnGroupContainer.less
> +}
```suggestion
.UIContainer.UIResponsiveColumnGroupContainer {
  .UIRowContainer.flexColumnContainer  {
    display: flex;
    flex-direction: row;
   } 
}
```

please format all less files

2022-12-21 15:39 UTC, sofyenne commented on platform-ui-skin/src/main/webapp/skin/less/platform/skin/uiSimpleContainers/simpleColumnContainer.less
> +  .UIContainer.SimpleColumnContainer {
done !

2022-12-21 15:51 UTC, azayati approved these changes
LGTM

2022-12-21 15:52 UTC, merged