feat:Implement people advanced filter drawer - EXO-60555 - Meeds-io/MIPs#39
Meeds-io/platform-ui pull request #594
Opened 2023-01-18 15:42 UTC by sofyenne

This change is going to add the css style for the reset people advanced filter button .

2023-01-18 16:50 UTC, azayati requested changes

2023-01-18 16:50 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +#resetButtonFilterPeopl {
```suggestion
.peopleAdvancedFilterResetButton {
```
try to move it directly under #peopleListApplication

2023-01-18 18:39 UTC, sofyenne commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +#resetButtonFilterPeopl {
fixed !

2023-01-19 14:16 UTC, azayati requested changes

2023-01-19 14:16 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +    background-color: #FFFFFF!important;
we should try to use color codes here

2023-01-19 15:17 UTC, sofyenne commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +    background-color: #FFFFFF!important;
fixed !

2023-01-19 15:30 UTC, azayati requested changes

2023-01-19 15:30 UTC, azayati commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +    background-color: @baseBackgroundDefault!important;
```suggestion
    box-shadow: 0 0 @baseBackgroundDefault !important;
    background-color: @baseBackgroundDefault !important;
```

2023-01-19 15:32 UTC, sofyenne commented on platform-ui-skin/src/main/webapp/skin/less/social/skin/PeopleList/Style.less
> +    background-color: @baseBackgroundDefault!important;
fixed !

2023-01-19 15:37 UTC, azayati approved these changes
LGTM

2023-01-19 15:39 UTC, merged